on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref_name == "main"
    steps:
      - uses: actions/checkout@v3

      - run: docker login -u ehyland -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: images/verdaccio-test/scripts/build.sh push
